apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: lb-pod
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lb-pod-svc
spec:
  type: LoadBalancer
  selector:
    app: myapp
  ports:
  - port: 80
  
