apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql-pod
  name: mydb
spec:
  containers:
  - name: con1
    image: mysql:5.7
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: test123
    - name: MYSQL_DATABASE
      value: aneesh


---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
spec:
  type: ClusterIP
  selector:
    app: mysql-pod
  ports:
  - port: 3306


