apiVersion: v1
kind: Pod
metadata:
  labels:
    app: myapp
  name: res-limit-pod
spec:
  containers:
  - name: con1
    image: nginx:latest
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "200m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: con2
    image: tomcat
    ports: 
    - containerPort: 8080
